/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 balloon.gltf --transform
Author: Jacob Thompson (https://sketchfab.com/jthomps)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hot-air-balloon-3861f77828a9460ca3875f9eef00cef4
Title: Hot Air Balloon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/balloon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 14.59, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.37, 1.37, 1.16]}>
          <mesh geometry={nodes.Box002__0.geometry} material={materials['Scene_-_Root']} position={[-9.55, -47.28, -17.25]} />
        </group>
        <group position={[0, 17.33, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1.37}>
          <mesh geometry={nodes.Box005__0.geometry} material={materials['Scene_-_Root']} position={[-9.55, -36.53, -27.96]} />
        </group>
        <group position={[0, 21.96, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[1.37, 1.37, 2.75]}>
          <mesh geometry={nodes.Box006__0.geometry} material={materials['Scene_-_Root']} position={[-9.55, -36.53, -27.96]} />
        </group>
        <group position={[-0.01, 24.71, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.37, 1.37, 1.22]}>
          <mesh geometry={nodes.Cylinder020__0.geometry} material={materials['Scene_-_Root']} position={[-43.73, -34.04, -25.06]} />
        </group>
        <mesh geometry={nodes.Cylinder001__0.geometry} material={materials['Scene_-_Root']} position={[0, 29.87, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.87} />
        <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Scene_-_Root']} position={[4.79, 11.52, -3.89]} rotation={[-1.39, -0.17, 0.03]} scale={[0.07, 0.07, 1.37]} />
        <mesh geometry={nodes.Cylinder003__0.geometry} material={materials['Scene_-_Root']} position={[4.73, 11.52, 3.95]} rotation={[-1.75, -0.17, -Math.PI / 2]} scale={[0.07, 0.07, 1.37]} />
        <mesh geometry={nodes.Cylinder004__0.geometry} material={materials['Scene_-_Root']} position={[-4.76, 11.52, 3.95]} rotation={[-1.75, 0.17, -3.11]} scale={[0.07, 0.07, 1.37]} />
        <mesh geometry={nodes.Cylinder005__0.geometry} material={materials['Scene_-_Root']} position={[-4.76, 11.52, -3.93]} rotation={[-1.4, 0.17, Math.PI / 2]} scale={[0.07, 0.07, 1.37]} />
        <mesh geometry={nodes.Cylinder006__0.geometry} material={materials['Scene_-_Root']} position={[-4.83, 17.29, -3.9]} rotation={[0, 0.87, -Math.PI / 2]} scale={[0.06, 0.06, 0.32]} />
        <mesh geometry={nodes.Cylinder007__0.geometry} material={materials['Scene_-_Root']} position={[5.09, 17.29, -4.23]} rotation={[0, -Math.PI / 4, -Math.PI / 2]} scale={[0.06, 0.06, 0.32]} />
        <mesh geometry={nodes.Cylinder008__0.geometry} material={materials['Scene_-_Root']} position={[-4.94, 17.29, 4.08]} rotation={[-Math.PI, Math.PI / 4, Math.PI / 2]} scale={[0.06, 0.06, 0.32]} />
        <mesh geometry={nodes.Cylinder009__0.geometry} material={materials['Scene_-_Root']} position={[3.72, 17.29, 2.99]} rotation={[0, 0.87, -Math.PI / 2]} scale={[0.06, 0.06, 0.32]} />
        <mesh geometry={nodes.Cylinder010__0.geometry} material={materials['Scene_-_Root']} position={[3.84, 17.36, -3]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.45, 0.45, 0.86]} />
        <mesh geometry={nodes.Cylinder011__0.geometry} material={materials['Scene_-_Root']} position={[-3.86, 17.36, -3.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.45, 0.45, 0.86]} />
        <mesh geometry={nodes.Cylinder012__0.geometry} material={materials['Scene_-_Root']} position={[-3.86, 17.36, 3.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.45, 0.45, 0.86]} />
        <mesh geometry={nodes.Cylinder013__0.geometry} material={materials['Scene_-_Root']} position={[3.82, 17.36, 3.05]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.45, 0.45, 0.86]} />
        <mesh geometry={nodes.Cylinder015__0.geometry} material={materials['Scene_-_Root']} position={[-3.82, 22.21, -3.01]} rotation={[-1.75, -0.17, -0.03]} scale={[0.01, 0.01, 0.09]} />
        <mesh geometry={nodes.Cylinder016__0.geometry} material={materials['Scene_-_Root']} position={[-3.82, 22.21, 3]} rotation={[-1.4, -0.17, Math.PI / 2]} scale={[0.01, 0.01, 0.09]} />
        <mesh geometry={nodes.Cylinder017__0.geometry} material={materials['Scene_-_Root']} position={[3.84, 22.21, -3.05]} rotation={[-1.75, 0.17, -Math.PI / 2]} scale={[0.01, 0.01, 0.09]} />
        <mesh geometry={nodes.Cylinder018__0.geometry} material={materials['Scene_-_Root']} position={[3.84, 22.21, 3.06]} rotation={[-1.39, 0.17, 3.11]} scale={[0.01, 0.01, 0.09]} />
      </group>
    </group>
  )
}

useGLTF.preload('/balloon-transformed.glb')
